# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-10 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('crm', '0002_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户拥有的角色'),
        ),
    ]
