# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-10 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('qq', 'qq群'), ('referral', '内部转介绍'), ('website', '官方网站'), ('baidu_ads', '百度推广'), ('office_direct', '直接上门'), ('WoM', '口碑'), ('public_class', '公开课'), ('website', '官网'), ('others', '其它')], default='qq', max_length=64, verbose_name='客户来源'),
        ),
    ]
